---
output: github_document
---

## Hello R!

Materials for the R bootcamp can be found below.
We will cover the material over the span of 4 half days.

For the "your turn" exercises we'll use RStudio Cloud.
Join the workspace [here](https://rstd.io/dsbox-cloud).

## Schedule

### Day 1

<table><thead><tr class="header"><th style="text-align: left;"><p>Time</p><p>
</p></th><th style="text-align: left;"><p>Activity</p><p>
</p></th></tr></thead><tbody><tr class="odd"><td style="text-align: left;"><p>09:30 - 10:30</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/01-whole-game/01-whole-game.html">The whole game</a></p><p>
</p></td></tr><tr class="even"><td style="text-align: left;"><p>10:30 - 10:45</p><p>
</p></td><td style="text-align: left;"><p><code>r emo::ji("coffee")</code> Coffee break</p><p>
</p></td></tr><tr class="odd"><td style="text-align: left;"><p>10:45 - 12:30</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/02-visualize-data/02-visualize-data.html">Visualize data</a></p><p>
</p></td></tr></tbody></table>

Prepare for the next day by recapping what you've learned so far:

-   Complete the tutorial [here](https://minecr.shinyapps.io/dsbox-01-edibnb/)
-   Complete `AE 02 - Bechdel + R Markdown` on RStudio Cloud [here](https://rstd.io/dsbox-cloud)

### Day 2

<table><thead><tr class="header"><th style="text-align: left;"><p>Time</p><p>
</p></th><th style="text-align: left;"><p>Activity</p><p>
</p></th></tr></thead><tbody><tr class="odd"><td style="text-align: left;"><p>09:30 - 10:45</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/03-wrangle-data/03-wrangle-data.html">Wrangle data</a>, Pt. 
1</p><p>
</p></td></tr><tr class="even"><td style="text-align: left;"><p>10:45 - 11:00</p><p>
</p></td><td style="text-align: left;"><p><code>r emo::ji("coffee")</code> Coffee break</p><p>
</p></td></tr><tr class="odd"><td style="text-align: left;"><p>11:00 - 12:30</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/03-wrangle-data/03-wrangle-data.html">Wrangle data</a>, Pt. 
2</p><p>
</p></td></tr></tbody></table>

-   Complete the tutorial on road traffic accidents [here](https://minecr.shinyapps.io/dsbox-02-accidents/)
-   Complete the tutorial on college majors [here](https://minecr.shinyapps.io/dsbox-03-collegemajors/)

### Day 3

<table><thead><tr class="header"><th style="text-align: left;"><p>Time</p><p>
</p></th><th style="text-align: left;"><p>Activity</p><p>
</p></th></tr></thead><tbody><tr class="odd"><td style="text-align: left;"><p>09:30 - 10:45</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/04-join-data/04-join-data.html">Join data</a></p><p>
</p></td></tr><tr class="even"><td style="text-align: left;"><p>10:45 - 11:00</p><p>
</p></td><td style="text-align: left;"><p><code>r emo::ji("coffee")</code> Coffee break</p><p>
</p></td></tr><tr class="odd"><td style="text-align: left;"><p>11:00 - 12:30</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/05-tidy-data/05-tidy-data.html">Tidy data</a></p><p>
</p></td></tr></tbody></table>

-   Complete the tutorial on bike share data [here](https://minecr.shinyapps.io/dsbox-06-dcbikeshare/)

### Day 4

<table><thead><tr class="header"><th style="text-align: left;"><p>Time</p><p>
</p></th><th style="text-align: left;"><p>Activity</p><p>
</p></th></tr></thead><tbody><tr class="odd"><td style="text-align: left;"><p>09:30 - 10:45</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/06-data-types/06-data-types.html">Data types</a></p><p>
</p></td></tr><tr class="even"><td style="text-align: left;"><p>10:45 - 11:00</p><p>
</p></td><td style="text-align: left;"><p><code>r emo::ji("coffee")</code> Coffee break</p><p>
</p></td></tr><tr class="odd"><td style="text-align: left;"><p>11:00 - 12:30</p><p>
</p></td><td style="text-align: left;"><p><a href="https://mine-cetinkaya-rundel.github.io/bootcamper-nui-galway/slides/07-import-data/07-import-data.html">Import data</a></p><p>
</p></td></tr></tbody></table>
